### ISSUE TITLE
question about cuda_sg_wrapper

### ISSUE THREAD

**Issue by zjin-lcf** [hpcgarage/spatter#112]
I cloned the main repo, and found that cuda_sg_wrapper is not called in main.c. Thank you for pointing me to the file that simply call the kernels in cuda_sg_wrapper.

**Comment by plavin** [comment]
That kernel is no longer called by main.c I believe because it didn't achieve high performance. The "blocking" done by the `*_block` kernels, which just means one thread performs several gathers/scatters, is needed to properly hide memory access latency. 

I'll open an issue to remove unused wrapper and kernel functions.

**Comment by plavin** [comment]
See #113
